<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2020-12-22
* Specification: ttps://github.com/amzn/selling-partner-api-models/blob/main/models/merchant-fulfillment-api-model/merchantFulfillmentV0.json
* Source MD5 signature: bce3fc0c3b42bc85895b4d9d74603f04
*
*
* Selling Partner API for Merchant Fulfillment
* The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class MerchantFulfillment extends Client {

  /**
  * Operation getEligibleShipmentServicesOld
   * @param $version
   * @return mixed
  */
  public function getEligibleShipmentServicesOld($body = [], $version = 'v0')
  {
    return $this->send("/mfn/{$version}/eligibleServices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getEligibleShipmentServices
   * @param $version
   * @return mixed
  */
  public function getEligibleShipmentServices($body = [], $version = 'v0')
  {
    return $this->send("/mfn/{$version}/eligibleShippingServices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getShipment
  *
  * @param string $shipmentId The Amazon-defined shipment identifier for the shipment.
   * @param $version
   * @return mixed
  */
  public function getShipment($shipmentId, $version = 'v0')
  {
    return $this->send("/mfn/{$version}/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation cancelShipment
  *
  * @param string $shipmentId The Amazon-defined shipment identifier for the shipment to cancel.
   * @param $version
   * @return mixed
  */
  public function cancelShipment($shipmentId, $version = 'v0')
  {
    return $this->send("/mfn/{$version}/shipments/{$shipmentId}", [
      'method' => 'DELETE',
    ]);
  }

  /**
  * Operation cancelShipmentOld
  *
  * @param string $shipmentId The Amazon-defined shipment identifier for the shipment to cancel.
   * @param $version
   * @return mixed
  */
  public function cancelShipmentOld($shipmentId, $version = 'v0')
  {
    return $this->send("/mfn/{$version}/shipments/{$shipmentId}/cancel", [
      'method' => 'PUT',
    ]);
  }

  /**
  * Operation createShipment
   * @param $version
   * @return mixed
  */
  public function createShipment($body = [], $version = 'v0')
  {
    return $this->send("/mfn/{$version}/shipments", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getAdditionalSellerInputsOld
   * @param $version
   * @return mixed
  */
  public function getAdditionalSellerInputsOld($body = [], $version = 'v0')
  {
    return $this->send("/mfn/{$version}/sellerInputs", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getAdditionalSellerInputs
   * @param $version
   * @return mixed
  */
  public function getAdditionalSellerInputs($body = [], $version = 'v0')
  {
    return $this->send("/mfn/{$version}/additionalSellerInputs", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
