<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2020-12-22
* Specification: ttps://github.com/amzn/selling-partner-api-models/blob/main/models/shipping-api-model/shipping.json
* Source MD5 signature: 753237a5a026d2529a2f179869e41358
*
*
* Selling Partner API for Shipping
* Provides programmatic access to Amazon Shipping APIs.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class Shipping extends Client {

  /**
  * Operation createShipment
  *
  */
  public function createShipment($body = [], $version = 'v1')
  {
    return $this->send("/shipping/{$version}/shipments", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getShipment
  *
  * @param string $shipmentId 
  *
  */
  public function getShipment($shipmentId, $version = 'v1')
  {
    return $this->send("/shipping/{$version}/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation cancelShipment
  *
  * @param string $shipmentId 
  *
  */
  public function cancelShipment($shipmentId, $version = 'v1')
  {
    return $this->send("/shipping/{$version}/shipments/{$shipmentId}/cancel", [
      'method' => 'POST',
    ]);
  }

  /**
  * Operation purchaseLabels
  *
  * @param string $shipmentId 
  *
  */
  public function purchaseLabels($shipmentId, $body = [], $version = 'v1')
  {
    return $this->send("/shipping/{$version}/shipments/{$shipmentId}/purchaseLabels", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation retrieveShippingLabel
  *
  * @param string $shipmentId 
  * @param string $trackingId 
  *
  */
  public function retrieveShippingLabel($shipmentId, $trackingId, $body = [], $version = 'v1')
  {
    return $this->send("/shipping/{$version}/shipments/{$shipmentId}/containers/{$trackingId}/label", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation purchaseShipment
  *
  */
  public function purchaseShipment($body = [], $version = 'v1')
  {
    return $this->send("/shipping/{$version}/purchaseShipment", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getRates
  *
  */
  public function getRates($body = [], $version = 'v1')
  {
    return $this->send("/shipping/{$version}/rates", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getAccount
  *
  */
  public function getAccount($version = 'v1')
  {
    return $this->send("/shipping/{$version}/account", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation getTrackingInformation
  *
  * @param string $trackingId 
  *
  */
  public function getTrackingInformation($trackingId, $version = 'v1')
  {
    return $this->send("/shipping/{$version}/tracking/{$trackingId}", [
      'method' => 'GET',
    ]);
  }
}
